### ISSUE TITLE
Sidan kraschar på /schedule/open-space

### ISSUE THREAD

**Issue by andreasolund** [acino/ae16#2]
Hej! Grymt bra arrangemang igår på konferensen! Blev nyfiken på hur sidan var uppbyggd och tittade igenom koden med devtools. Upptäckte då att sidan kraschar på: 
http://agileexchange.acino.se/schedule/open-space.

Vid en närmare titt så ser jag att i [session-detail.ts#L11](https://github.com/acino/ae16/blob/master/src/app/schedule/session-detail.html#L11) 
så skickas sessionsbeskrivningen in till pipen linkify. Dock så finns det ingen beskrivning för open-space i [sessions.json#L83-L87](https://github.com/acino/ae16/blob/master/src/assets/json/sessions.json#L83-L87) så indatat till linkify blir `undefined`!

**Comment by karllindmark** [comment]
Tack @andreasolund, och snyggt hittat! 

Vi ser till att åtgärda det ASAP... om du inte vill fixa problemet via en PR förstås! :))

**Comment by andreasolund** [comment]
Skickat en PR där jag helt enkelt döljer description-paragrafen om den inte är satt i datafilen. Som ett komplement till ändringen så borde kanske linkify kontrollera att input är en sträng som krävs för att replace-metoden ska vara tillgänglig! :)

**Comment by karllindmark** [comment]
Löst i #3!

(Ps. Det ska gå att auto-stänga issues via meddelandet i PR:en, men jag är inte alls säker på hur man går tillväga med det)
